---
- name: GCP Playbook
  hosts: linux
  become: yes
  gather_facts: true
  vars:
    file: test_rsa_key
    notafile: does_not_exist

  tasks:
  - name: Check presence of existing file in GCP
    command: /usr/local/gcloud/google-cloud-sdk/bin/gsutil ls -L gs://sshkeys_test/{{ file }}
    register: presence_result
    ignore_errors: true

  - name: Copying file to bucket
    command: /usr/local/gcloud/google-cloud-sdk/bin/gsutil cp /etc/ssh/{{ file }} gs://sshkeys_test/{{ file }}
    register:  copy_result
    when: presence_result.rc == 1
  - meta: end_play
    when: presence_result.rc == 1
  
  - name: Get remote file MD5 value
    shell: >
        /usr/local/gcloud/google-cloud-sdk/bin/gsutil hash -m gs://sshkeys_test/{{ file }} | 
        awk 'FNR == 3 {print $3}'
    register: remote_md5
  
  # - name: Debug remote_md5 output
  #   debug:
  #     var: remote_md5.stdout_lines

  - name: Get local file MD5 value
    shell: >
        /usr/local/gcloud/google-cloud-sdk/bin/gsutil hash -m /etc/ssh/{{ file }} | 
        awk 'FNR == 2 {print $3}'
    register: local_md5
  
  # - name: Debug local_md5 output
  #   debug:
  #     var: local_md5.stdout_lines

  - meta: end_play
    when: remote_md5.stdout_lines == local_md5.stdout_lines
  
  - name: Copying file from bucket
    command: /usr/local/gcloud/google-cloud-sdk/bin/gsutil cp gs://sshkeys_test/{{ file }} /etc/ssh/{{ file }}
...
