# This playbook installs and enables WSUS on Windows hosts

- name: Install WSUS
  hosts: wsus
  vars:
       reportviewer_download: <REDACTED>
  gather_facts: false
  tasks:
    - name: Install WSUS
      win_feature:
        name: UpdateServices
        state: present
        include_management_tools: yes

    - name: Create WSUS directory
      win_file:
       path: D:\WSUS
       state: directory

    - name: Change the working directory to C:\Program Files\Update Services\Tools\ before executing WsusUtil.
      win_shell: .\WsusUtil.exe PostInstall CONTENT_DIR=C:\WSUS
      args:
        chdir: C:\Program Files\Update Services\Tools\

    - name: Install .NetFW 3.5 for Report Viewer 2008
      win_feature:
        name: NET-Framework-Core
        state: present

    - name: Download Report Viewer 2008 to specified path
      win_get_url:
        url: "{{ reportviewer_download }}"
        dest: C:\Windows\Temp\ReportViewer.exe
        force: yes
        skip_certificate_validation: true

    - name: Install Report Viewer 2008
      win_package:
        path: C:\Windows\Temp\ReportViewer.exe
        product_id: '{5E152D08-572A-3375-8FDE-DAD1EFB379BA}'
        arguments: /q

    - name: Run powershell script to configure WSUS
      script: scripts/configureWsus.ps1



