- name: Add server to the domain
  win_domain_membership:
    dns_domain_name: "{{ dns_domain_name }}"
    hostname: "{{ ansible_hostname }}"
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
    domain_ou_path: "{{ domain_ou_path }}"
    state: domain
  register: domain_state

- debug: msg="{{ domain_state }}"

- win_reboot:
  when: domain_state.reboot_required
